db_logic:
    resource: "@DBLogicBundle/Controller/"
    type:     annotation
    prefix:   /

#flat_parcer:
#    resource: "@FlatParserBundle/Controller/"
#    type:     annotation
#    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
